# Generated by Django 4.1 on 2022-08-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('user_name', models.TextField(max_length=40, verbose_name='@ пользователя')),
                ('first_name', models.TextField(max_length=40, null=True, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('order_value', models.CharField(max_length=200, verbose_name='Заказ')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.users', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200, verbose_name='Текст сообщения')),
                ('is_sender', models.BooleanField(verbose_name='Является ли пользователь отправителем')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата и время отправки')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders', verbose_name='ID заказа')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.users', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
