# Generated by Django 4.1 on 2022-08-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Заказ выполнен'),
        ),
    ]
