# Generated by Django 4.1 on 2022-08-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_order_active',
            field=models.BooleanField(default=False, verbose_name='Сбор данных по заказу'),
        ),
    ]
