# Generated by Django 4.1 on 2022-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_orders_options_orders_date_orders_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=True, verbose_name='Сообщение прочитано?'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.IntegerField(default=1, max_length=3, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='is_sender',
            field=models.BooleanField(verbose_name='Является ли пользователь отправителем?'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_closed',
            field=models.BooleanField(verbose_name='Заказ выполнен'),
        ),
    ]
