# Generated by Django 4.1 on 2022-08-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_users_is_order_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_chat_active',
            field=models.BooleanField(default=False, verbose_name='Активная переписка'),
        ),
    ]
