# Generated by Django 4.1 on 2022-08-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orders_is_chat_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Заказ выполнен'),
        ),
    ]
